name: Publish

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CHCEKOUT
        uses: actions/checkout@master
      - name: DEPLOY
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./
