name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  steps:
    - name: Checkout 🛎
      uses: actions/checkout@master

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ./
